# Environment Variables
export ZSH="/Users/raveneyex/.oh-my-zsh"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/"
export UPDATE_ZSH_DAYS=15
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"

CASE_SENSITIVE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

# POWERLEVEL10K

ZSH_THEME="powerlevel10k/powerlevel10k"
POWERLEVEL9K_MODE=nerdfont-complete

# Variables
DEFAULT_BACKGROUND="black"
DEFAULT_FOREGROUND="white"
USERNAME_COLOR="088"
USERNAME_ICON_COLOR="white"
GIT_MODIFIED_COLOR="red"
RIGHT_BACKGROUND="black"
RIGHT_FOREGROUND="red"
USER_ICON="\ue36e"
SYSTEM_ICON="\uF109"
SPOTIFY_ICON="\uf9c6"

# Prompt settings
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="╭"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="╰\uF460 "

# Separators
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\ue0b0'
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=$'\uf6d8'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\ue0b2'
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=$'\uf6d8'

# OS Segment
POWERLEVEL9K_APPLE_ICON="%F{$DEFAULT_FOREGROUND}\uf179%f"
POWERLEVEL9K_LINUX_ICON="%F{$DEFAULT_FOREGROUND}\uf31b%f"
POWERLEVEL9K_OS_ICON_BACKGROUND="$DEFAULT_BACKGROUND"

# Context
POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
POWERLEVEL9K_ALWAYS_SHOW_USER=false
POWERLEVEL9K_CONTEXT_TEMPLATE="%F{$USERNAME_ICON_COLOR}${USER_ICON} %F{$USERNAME_COLOR}%n %F{$DEFAULT_FOREGROUND}\uf6d8 $SYSTEM_ICON  %m %f"

# Dir colours
POWERLEVEL9K_DIR_HOME_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_DIR_HOME_FOREGROUND="$DEFAULT_FOREGROUND"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="$DEFAULT_FOREGROUND"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="$DEFAULT_FOREGROUND"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_HOME_ICON="\uf286 "
POWERLEVEL9K_HOME_SUB_ICON="\uf07c "

# VCS icons
POWERLEVEL9K_VCS_GIT_ICON=$''
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=$''
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=$''
POWERLEVEL9K_VCS_BRANCH_ICON=$'\ue725 '
POWERLEVEL9K_VCS_STAGED_ICON=$'\uf055 '
POWERLEVEL9K_VCS_UNSTAGED_ICON=$'\uf421 '
POWERLEVEL9K_VCS_UNTRACKED_ICON=$'\uf00d '
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=$'\uf0ab '
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=$'\uf0aa '
# VCS colours
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="$DEFAULT_FOREGROUND"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="$DEFAULT_FOREGROUND"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="$GIT_MODIFIED_COLOR"
# VCS CONFIG
POWERLEVEL9K_SHOW_CHANGESET=false

# Battery
POWERLEVEL9K_BATTERY_LOW_FOREGROUND="$RIGHT_FOREGROUND"
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND="$RIGHT_FOREGROUND"
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND="$RIGHT_FOREGROUND"
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND="$RIGHT_FOREGROUND"
POWERLEVEL9K_BATTERY_VERBOSE=true

# TIME
POWERLEVEL9K_TIME_BACKGROUND="$RIGHT_BACKGROUND"
POWERLEVEL9K_TIME_FOREGROUND="$RIGHT_FOREGROUND"

# NVM
POWERLEVEL9K_NVM_BACKGROUND="$RIGHT_BACKGROUND"
POWERLEVEL9K_NVM_FOREGROUND="$RIGHT_FOREGROUND"
POWERLEVEL9K_NODE_ICON=$'\ue718 '

# Prompt elements
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs battery time nvm)

plugins=(
  git
  mvn
)

ZSH_THEME="powerlevel10k/powerlevel10k"

source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Aliases and functions
source $HOME/.commands

nvm use default

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
